# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# removed for Jekyll v3.0
#relative_permalinks: true

# Setup
title:               akaAK
tagline:             AK Adapa engineering, tech, findings blog
paginate:            1
url:                 http://akaak.github.io/blog/
baseurl:             http://akaak.github.io/blog
# baseurl has to be blank for localhost to work
#baseurl:             ""

# added for Jekyll v3.0
gems: [jekyll-paginate]
paginate_path: "page:num"

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              AK Adapa
  url:               https://twitter.com/akadapa
  email:             akadapa@gmail.com

# Custom vars
version:             1.3.0
github:
  repo:              https://github.com/akaak

# List of pages to include in the header.
pages_list:       
  About: '/about/'
  Archive: '/archive/'
  #Feed: '/atom.xml'